### ISSUE TITLE
Test case (testAbPattern) 944413907 will trigger error

### ISSUE THREAD

**Issue by boltomli** [aadnk/Bitspeak4j#1]
Think there's a limit of input. Guess that I use the method in a wrong way, though.

```
java.lang.NegativeArraySizeException: -2011087715

	at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:112)
	at com.comphenix.bitspeak.Bitspeak.encode(Bitspeak.java:446)
	at com.comphenix.bitspeak.Bitspeak.encode(Bitspeak.java:434)
```

**Comment by aadnk** [comment]
I was able to reproduce this when encoding a fairly large array (513 MB) to BS-8:
```java
 byte[] data = new byte[514 * 1024 * 1024];
 String test = Bitspeak.bs8().withConfig(BitspeakConfig.unlimitedWordSize()).encode(data);
```
I assume that's roughly what you were doing? 

I can certainly fix this, though there is no guarantee you will be able to successfully encode an array larger than 512 MB to BS-8, as some consonants and vowels are two characters long, making it possible that a converted byte might be as long as 4 characters. For instance, the byte 0x66 is represented by the bit pattern 0110 0110, which in BS-8 gets converted to "shen". Thus, a byte array containing only 0x66 would get converted to "shen" * the total length of the byte array. If the byte array was 513 MB, this would be 2052 MB, and exceed the maximum possible length of a string (2^31 - 1, or 2047 MB). 

In any case, I recommend using InputStream and Reader instead of byte arrays if you have very large data sizes:
```java
byte[] data = new byte[1024 * 1024 * 1024];

Path output = Paths.get("C:\\Temp\\Output.txt");
Bitspeak bs8 = Bitspeak.bs8();

try (Reader reader = bs8.newEncodeStream(new ByteArrayInputStream(data));
    BufferedWriter writer = Files.newBufferedWriter(output)) {
    CharStreams.copy(reader, writer); // Guava
}
```
